repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: name-tests-test
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.1
    hooks:
      - id: ruff # linter
        types_or: [python, pyi, jupyter]
        args: [--fix]
      - id: ruff-format # formatter
        types_or: [python, pyi, jupyter]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: python
        types_or: [python, pyi]
        args: []
        require_serial: true
        additional_dependencies: []
        minimum_pre_commit_version: 2.9.2

  - repo: https://github.com/dosisod/refurb
    rev: v1.28.0
    hooks:
      - id: refurb

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        stages: [push]
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
